services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium_hub_container
    user: root
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
  chrome:
    image: selenium/node-chrome:latest
    shm_size: "2g"
    environment:
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_EVENT_BUS_HOST=selenium-hub
  firefox:
    image: selenium/node-firefox:latest
    shm_size: "2g"
    environment:
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_EVENT_BUS_HOST=selenium-hub