pipeline {
  agent {
    docker {
      image 'yehory/api_tests_java:2.0'
      label 'macOS'
      reuseNode true
    }
  }

  options { timestamps() }

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/YehorYehorychev/Docker-Project-Coffee.git'
      }
    }

    stage('Run tests') {
      steps {
        sh 'mvn -version'
        sh 'mvn clean test -Dsurefire.suiteXmlFiles=testng.xml'
      }
    }

    stage('Archive & Publish reports') {
      steps {
        junit 'target/surefire-reports/TEST-*.xml'

        archiveArtifacts artifacts: 'target/surefire-reports/**', fingerprint: true

        publishHTML(target: [
          reportDir: 'target/surefire-reports',
          reportFiles: 'emailable-report.html',
          reportName: 'API Test Report',
          keepAll: true,
          alwaysLinkToLastBuild: true
        ])
      }
    }
  }
}