name: jenkins

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins_container
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./volumes/master:/var/jenkins_home